TokenId = int

class BestChoice: ...
class CountInfo: ...
class InferRequest: ...
class InferResponse: ...
class Prediction: ...
class VocabPrefixAutomaton: ...
class ReorderedTokenId: ...
class SearchTree: ...
