from typing import Sequence, Tuple

TokenId = int
SortedTokenId = int

class SortedTokenRange:
    lower: SortedTokenId
    upper: SortedTokenId

class VocabPrefixAutomaton:
    def __init__(self, vocab: Sequence[bytes]) -> None: ...
    @property
    def vocab_size(self) -> int: ...
    def get_order(self) -> Sequence[TokenId]: ...
    def get_rank(self) -> Sequence[SortedTokenId]: ...
    def parse_bytes(self, inputs: bytes) -> Sequence[Tuple[int, SortedTokenRange]]: ...
    def parse_tokens(
        self, token_ids: Sequence[TokenId]
    ) -> Sequence[Tuple[bytes, SortedTokenRange]]: ...
