from typing import Sequence

TokenId = int

class BestChoice: ...
class CountInfo: ...
class InferRequest: ...
class InferResponse: ...
class Prediction: ...

class VocabPrefixAutomaton:
    def __init__(self, vocab: Sequence[str]) -> None: ...
    def get_order(self) -> Sequence[int]: ...
    @property
    def vocab_size(self) -> int: ...

class ReorderedTokenId: ...
class SearchTree: ...
